# Generated by Django 5.0 on 2024-04-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_chapter_chap_rename_imageschapter_imageschap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='category',
            new_name='categories',
        ),
    ]
